/*
** CREATED BY: ALEX NEWSHAM
** CREATED ON: 12/07/2018
** PURPOSE: GET THE DATE 12 WEEKS AGO FROM TODAY
*/

-- THE DATE 12 WEEKS AGO FROM TODAY
SELECT 'The date 12 weeks ago from today' AS DateType, CAST(DATEADD(DAY,0,GETDATE())-84 AS DATE) as Date12WeeksAgo
